[project]
name = "worldnavigator"
version = "0.2.0"
description = "A tool to help you navigate through a simulated world."
readme = "README.md"
authors = [{ name = "IkarosKurtz", email = "ikaroskurtz@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "rich>=14.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "esbonio>=0.16.5",
    "python-json-logger>=3.3.0",
    "sentry-sdk>=2.28.0",
    "sphinx>=8.2.3",
    "sphinx-autoapi>=3.6.0",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-rtd-theme>=3.0.2",
]
