[theme]
primaryColor = "#337ff3"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#434343"
textColor = "#fdfdb7"
font = "Montserrat serif"


[server]
headless = true
enableCORS = true
enableXsrfProtection = true
